spring: 
  datasource:
#    url: jdbc:h2:${user.dir}/dbs/persondbs;AUTO_SERVER=TRUE;AUTO_RECONNECT=TRUE;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:~/persondb;AUTO_SERVER=TRUE;AUTO_RECONNECT=TRUE;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:    
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: h2
  jmx:
    enabled: false
    default-domain: app
  #  server: appServer
    
demo: 
  app-name: myapp
  version: 0.0.1
  author: Simon Pascal Ngos
  lastest-update: 10/05/2016
  